name: Lint

on:
    pull_request:
        branches: [main]

jobs:
    Test:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            - name: Install uv
              uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

            - name: Check uv.lock
              run: uv lock --check

            - name: Install dependencies
              run: uv sync --locked

            - name: Lint with ruff
              run: uv run ruff check --output-format=github .

            - name: Format with ruff
              run: uv run ruff format --check .
